# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 260b336cd729c8844f15e3f8406f8d54047d7392e1cade71e71117214ea0233b2366df385c997f97010c778ae3dd5f9261495a6f549d8e98e60131621d2db2fe

test:
  secret_key_base: f0b6fc2ea61fa40690e04061beea1785c60bf3f5349ef4057eab4189e384645d6014221c275733131ee6dabfb30675640cc9f4c8a39ced8277f102a8d89f7e3d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
